# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Wed May 27 22:25:13 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(364, 403)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(46)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label.setFrameShadow(QtGui.QFrame.Plain)
        self.label.setLineWidth(1)
        self.label.setText(_fromUtf8(""))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.numButton_9 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_9.sizePolicy().hasHeightForWidth())
        self.numButton_9.setSizePolicy(sizePolicy)
        self.numButton_9.setObjectName(_fromUtf8("numButton_9"))
        self.gridLayout.addWidget(self.numButton_9, 2, 2, 1, 1)
        self.numButton_4 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_4.sizePolicy().hasHeightForWidth())
        self.numButton_4.setSizePolicy(sizePolicy)
        self.numButton_4.setObjectName(_fromUtf8("numButton_4"))
        self.gridLayout.addWidget(self.numButton_4, 1, 0, 1, 1)
        self.numButton_1 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_1.sizePolicy().hasHeightForWidth())
        self.numButton_1.setSizePolicy(sizePolicy)
        self.numButton_1.setObjectName(_fromUtf8("numButton_1"))
        self.gridLayout.addWidget(self.numButton_1, 0, 0, 1, 1)
        self.unlockButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unlockButton.sizePolicy().hasHeightForWidth())
        self.unlockButton.setSizePolicy(sizePolicy)
        self.unlockButton.setObjectName(_fromUtf8("unlockButton"))
        self.gridLayout.addWidget(self.unlockButton, 3, 2, 1, 1)
        self.numButton_2 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_2.sizePolicy().hasHeightForWidth())
        self.numButton_2.setSizePolicy(sizePolicy)
        self.numButton_2.setObjectName(_fromUtf8("numButton_2"))
        self.gridLayout.addWidget(self.numButton_2, 0, 1, 1, 1)
        self.numButton_5 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_5.sizePolicy().hasHeightForWidth())
        self.numButton_5.setSizePolicy(sizePolicy)
        self.numButton_5.setObjectName(_fromUtf8("numButton_5"))
        self.gridLayout.addWidget(self.numButton_5, 1, 1, 1, 1)
        self.numButton_3 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_3.sizePolicy().hasHeightForWidth())
        self.numButton_3.setSizePolicy(sizePolicy)
        self.numButton_3.setObjectName(_fromUtf8("numButton_3"))
        self.gridLayout.addWidget(self.numButton_3, 0, 2, 1, 1)
        self.numButton_0 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_0.sizePolicy().hasHeightForWidth())
        self.numButton_0.setSizePolicy(sizePolicy)
        self.numButton_0.setObjectName(_fromUtf8("numButton_0"))
        self.gridLayout.addWidget(self.numButton_0, 3, 1, 1, 1)
        self.numButton_6 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_6.sizePolicy().hasHeightForWidth())
        self.numButton_6.setSizePolicy(sizePolicy)
        self.numButton_6.setObjectName(_fromUtf8("numButton_6"))
        self.gridLayout.addWidget(self.numButton_6, 1, 2, 1, 1)
        self.numButton_8 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_8.sizePolicy().hasHeightForWidth())
        self.numButton_8.setSizePolicy(sizePolicy)
        self.numButton_8.setObjectName(_fromUtf8("numButton_8"))
        self.gridLayout.addWidget(self.numButton_8, 2, 1, 1, 1)
        self.numButton_7 = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numButton_7.sizePolicy().hasHeightForWidth())
        self.numButton_7.setSizePolicy(sizePolicy)
        self.numButton_7.setObjectName(_fromUtf8("numButton_7"))
        self.gridLayout.addWidget(self.numButton_7, 2, 0, 1, 1)
        self.clearButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
        self.clearButton.setSizePolicy(sizePolicy)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.gridLayout.addWidget(self.clearButton, 3, 0, 1, 1)
        self.scanButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanButton.sizePolicy().hasHeightForWidth())
        self.scanButton.setSizePolicy(sizePolicy)
        self.scanButton.setObjectName(_fromUtf8("scanButton"))
        self.gridLayout.addWidget(self.scanButton, 4, 0, 1, 1)
        self.ringButton = QtGui.QPushButton(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringButton.sizePolicy().hasHeightForWidth())
        self.ringButton.setSizePolicy(sizePolicy)
        self.ringButton.setObjectName(_fromUtf8("ringButton"))
        self.gridLayout.addWidget(self.ringButton, 4, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(1, 5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.numButton_9.setText(_translate("Form", "9", None))
        self.numButton_4.setText(_translate("Form", "4", None))
        self.numButton_1.setText(_translate("Form", "1", None))
        self.unlockButton.setText(_translate("Form", "Unlock", None))
        self.numButton_2.setText(_translate("Form", "2", None))
        self.numButton_5.setText(_translate("Form", "5", None))
        self.numButton_3.setText(_translate("Form", "3", None))
        self.numButton_0.setText(_translate("Form", "0", None))
        self.numButton_6.setText(_translate("Form", "6", None))
        self.numButton_8.setText(_translate("Form", "8", None))
        self.numButton_7.setText(_translate("Form", "7", None))
        self.clearButton.setText(_translate("Form", "Clear", None))
        self.scanButton.setText(_translate("Form", "Scan QR", None))
        self.ringButton.setText(_translate("Form", "Ring", None))

